### PR TITLE
Use module_function in IceNine

### PR DESCRIPTION
**Pull request by soulcutter**
This enables a user to include IceNine in their classes to make its methods available to instances without the need to prefix invocations with IceNine.

I know your contributing docs ask to have a discussion with you before doing any work, but I hope that's the only rule I broke :see_no_evil: Consider this the start of a conversation about it maybe?

### CODE REVIEW

**Comment by dkubb** [comment]
> I know your contributing docs ask to have a discussion with you before doing any work, but I hope that's the only rule I broke

This is mainly to save you time, I don't mind people submitting PR's early if it's easier for them ;)

> This enables a user to include IceNine in their classes to make its methods available to instances without the need to prefix invocations with IceNine.

This is an interesting use case. So you are doing things like `include IceNine` and then using things like `deep_freeze` directly in the class? Does it bother you that having the `IceNine` methods adds to your public interface?

**Comment by soulcutter** [comment]
> So you are doing things like include IceNine and then using things like deep_freeze directly in the class? Does it bother you that having the IceNine methods adds to your public interface?

Yes, this is exactly it. I try to take encapsulation seriously and design public interfaces that are minimal and coherent. I don't always succeed, but it's an ideal.

You could say it's aesthetic to prefer not to use `IceNine.` as a prefix everywhere, but I think there's a small but real benefit. Particularly since IceNine is something of an interface for convenience that delegates to `IceNine::Freezer`.

**Comment by soulcutter** [comment]
Looks like my gem updates broke CI all over the place. I'm not sure how you manage versions in there - any advice? Maybe if I rolled back all the version changes and just fixed the git-referenced one, that might take care of it :/

**Comment by soulcutter** [comment]
Any thoughts about this?

**Comment by soulcutter** [comment]
Welp I have no idea how to use the devtools to fix this build, so no point letting this linger.

**Pull request closed without merging**
